In [9]:
#1
import numpy as np

In [12]:
#2
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#3
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#4
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr % 2 > 0)

(array([1, 3, 5, 7, 9]),)

In [26]:
#5
arr[arr % 2 > 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [22]:
#6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr %2 > 0, -1, arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [29]:
#7
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
#9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [45]:
#10
a = np.array([1,2,3])
np.r_[[a[0]]*3, [a[1]]*3,[a[2]]*3, a,a,a]
np.r_[a.repeat(3), np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])